"""Polymarket read-only client.

No auth required for public market data. Uses the CLOB REST endpoints.
Designed to be called from a daily cron that refreshes data/odds_snapshot.json.

Docs: https://docs.polymarket.com/api-reference/introduction
Gamma API (markets/events metadata): https://gamma-api.polymarket.com
CLOB API (order book / prices): https://clob.polymarket.com
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import urllib.request
import urllib.parse


GAMMA_BASE = "https://gamma-api.polymarket.com"


@dataclass
class MarketOutcome:
    name: str            # e.g. "France"
    token_id: str        # CLOB token id
    price: float         # current implied probability (0..1)


@dataclass
class Market:
    id: str
    slug: str
    question: str
    outcomes: list[MarketOutcome]
    volume_usd: float


def _get(url: str) -> Any:
    req = urllib.request.Request(url, headers={"User-Agent": "world-cup-loops/0.1"})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.loads(r.read().decode("utf-8"))


def fetch_event(event_slug: str = "2026-fifa-world-cup-winner-595") -> dict:
    """Fetch a Polymarket event by slug (the URL fragment)."""
    return _get(f"{GAMMA_BASE}/events?slug={urllib.parse.quote(event_slug)}")


def fetch_markets_for_event(event_id: str) -> list[Market]:
    """Fetch all markets under a Polymarket event."""
    raw = _get(f"{GAMMA_BASE}/markets?event_id={event_id}&limit=200")
    out: list[Market] = []
    for m in raw:
        outcomes = []
        try:
            outcome_names = json.loads(m.get("outcomes", "[]"))
            outcome_prices = json.loads(m.get("outcomePrices", "[]"))
            outcome_token_ids = json.loads(m.get("clobTokenIds", "[]"))
            for name, price, tok in zip(outcome_names, outcome_prices, outcome_token_ids):
                outcomes.append(
                    MarketOutcome(name=name, token_id=tok, price=float(price))
                )
        except (json.JSONDecodeError, KeyError, ValueError):
            continue
        out.append(
            Market(
                id=str(m.get("id")),
                slug=m.get("slug", ""),
                question=m.get("question", ""),
                outcomes=outcomes,
                volume_usd=float(m.get("volume", 0)),
            )
        )
    return out


def snapshot_world_cup_winner_to(path: Path, event_slug: str = "2026-fifa-world-cup-winner-595"):
    """Pull the winner market and write a snapshot compatible with data/odds_snapshot.json."""
    event_resp = fetch_event(event_slug)
    if not event_resp:
        raise RuntimeError(f"event not found: {event_slug}")
    event = event_resp[0] if isinstance(event_resp, list) else event_resp
    event_id = str(event["id"])
    markets = fetch_markets_for_event(event_id)
    if not markets:
        raise RuntimeError(f"no markets found for event {event_id}")

    winner_market = max(markets, key=lambda m: m.volume_usd)
    winner_pct = {}
    for o in winner_market.outcomes:
        code = _team_name_to_code(o.name)
        if code:
            winner_pct[code] = round(o.price * 100, 2)

    from datetime import date
    snapshot = {
        "_notes": "Auto-generated by polymarket_client.snapshot_world_cup_winner_to()",
        "last_updated": date.today().isoformat(),
        "source": f"polymarket-{event_slug}",
        "winner_market": winner_pct,
    }
    path.write_text(json.dumps(snapshot, indent=2))
    return snapshot


_NAME_TO_CODE = {
    "Spain": "ESP", "France": "FRA", "England": "ENG", "Brazil": "BRA",
    "Argentina": "ARG", "Portugal": "POR", "Netherlands": "NED",
    "Germany": "GER", "Italy": "ITA", "Belgium": "BEL", "Uruguay": "URU",
    "Croatia": "CRO", "United States": "USA", "Mexico": "MEX",
    "Colombia": "COL", "Japan": "JPN", "South Korea": "KOR",
    "Morocco": "MAR", "Denmark": "DEN", "Switzerland": "SUI",
    "Senegal": "SEN", "Austria": "AUT", "Ukraine": "UKR", "Poland": "POL",
    "Türkiye": "TUR", "Turkey": "TUR", "Ecuador": "ECU", "Australia": "AUS",
    "Canada": "CAN", "Scotland": "SCO", "Wales": "WAL", "Iran": "IRN",
    "Algeria": "ALG", "Egypt": "EGY", "Nigeria": "NGA", "Ivory Coast": "CIV",
    "Ghana": "GHA", "Tunisia": "TUN", "Peru": "PER", "Paraguay": "PAR",
    "Venezuela": "VEN", "Iraq": "IRQ", "Saudi Arabia": "KSA", "Qatar": "QAT",
    "Uzbekistan": "UZB", "Jordan": "JOR", "New Zealand": "NZL",
    "Costa Rica": "CRC", "Panama": "PAN",
}


def _team_name_to_code(name: str) -> str | None:
    return _NAME_TO_CODE.get(name.strip())


if __name__ == "__main__":
    import sys
    out = Path(__file__).resolve().parent.parent / "data" / "odds_snapshot.json"
    snap = snapshot_world_cup_winner_to(out)
    print(json.dumps(snap, indent=2))
